.TH blacklist-checker 1  ""
.SH "NAME"
blacklist-checker
.SH "SYNOPSIS"
.TP
\fBblacklist-checker [<flags>] <command> [<args> ...]\fR

.SH "DESCRIPTION"
Fast blacklist checker application
.SH "OPTIONS"
.TP
\fB-h, --help\fR
Show context-sensitive help (also try --help-long and --help-man).
.TP
\fB--verbose\fR
Verbose mode.
.TP
\fB-v, --version\fR
Show version and terminate
.TP
\fB--nameserver=8.8.8.8:53\fR
Name server to use
.TP
\fB--queue=25\fR
How many request to process at one time
.SH "COMMANDS"
.SS
\fBhelp [<command>...]\fR
.PP
Show help.
.SS
\fBip <ip-address>\fR
.PP
Check IP against available blacklists
.SS
\fBcidr <cidr-address>\fR
.PP
Check CIDR against available blacklists
.SS
\fBlist\fR
.PP
List available blacklists
